# Configuration for labeler - https://github.com/actions/labeler

📖 Docs: 
- changed-files:
  - any-glob-to-any-file: 'src/docs/**/*'
🌍 i18n: 
- changed-files:
  - any-glob-to-any-file: 'src/i18n/en-US/**/*'
Actions: 
- changed-files:
  - any-glob-to-any-file: '.github/workflows/**/*'